### ISSUE TITLE
TOR Not Being Utilised

### ISSUE THREAD

**Issue by ottar-eten-yod** [popcorn-time-ru/popcorn-ru#51]
```
22:03:42 ERROR     [app] cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to eztv.re:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://eztv.re/api/get-torrents?limit=100&page=1
[
  "trace" => """
    #0 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()\n
    #1 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()\n
    #2 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()\n
    #3 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()\n
    #4 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()\n
    #5 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()\n
    #6 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()\n
    #7 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()\n
    #8 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()\n
    #9 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()\n
    #10 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()\n
    #11 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()\n
    #12 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()\n
    #13 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()\n
    #14 /var/www/popcorntime/src/Spider/Eztv.php(41): GuzzleHttp\Client->get()\n
    #15 /var/www/popcorntime/src/Processors/ForumProcessor.php(53): App\Spider\Eztv->getPage()\n
    #16 /var/www/popcorntime/vendor/enqueue/enqueue/Client/DelegateProcessor.php(38): App\Processors\ForumProcessor->process()\n
    #17 /var/www/popcorntime/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(197): Enqueue\Client\DelegateProcessor->process()\n
    #18 [internal function]: Enqueue\Consumption\QueueConsumer->Enqueue\Consumption\{closure}()\n
    #19 /var/www/popcorntime/vendor/enqueue/dbal/DbalSubscriptionConsumer.php(117): call_user_func()\n
    #20 /var/www/popcorntime/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(264): Enqueue\Dbal\DbalSubscriptionConsumer->consume()\n
    #21 /var/www/popcorntime/vendor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php(144): Enqueue\Consumption\QueueConsumer->consume()\n
    #22 /var/www/popcorntime/vendor/symfony/console/Command/Command.php(298): Enqueue\Symfony\Client\ConsumeCommand->execute()\n
    #23 /var/www/popcorntime/vendor/symfony/console/Application.php(1042): Symfony\Component\Console\Command\Command->run()\n
    #24 /var/www/popcorntime/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()\n
    #25 /var/www/popcorntime/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()\n
    #26 /var/www/popcorntime/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()\n
    #27 /var/www/popcorntime/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()\n
    #28 /var/www/popcorntime/bin/console(42): Symfony\Component\Console\Application->run()\n
    #29 {main}
    """,
  "extra" => [
    "trace" => """
      #0 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()\n
      #1 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()\n
      #2 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()\n
      #3 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()\n
      #4 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()\n
      #5 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()\n
      #6 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()\n
      #7 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()\n
      #8 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()\n
      #9 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()\n
      #10 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()\n
      #11 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()\n
      #12 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()\n
      #13 /var/www/popcorntime/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()\n
      #14 /var/www/popcorntime/src/Spider/Eztv.php(41): GuzzleHttp\Client->get()\n
      #15 /var/www/popcorntime/src/Processors/ForumProcessor.php(53): App\Spider\Eztv->getPage()\n
      #16 /var/www/popcorntime/vendor/enqueue/enqueue/Client/DelegateProcessor.php(38): App\Processors\ForumProcessor->process()\n
      #17 /var/www/popcorntime/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(197): Enqueue\Client\DelegateProcessor->process()\n
      #18 [internal function]: Enqueue\Consumption\QueueConsumer->Enqueue\Consumption\{closure}()\n
      #19 /var/www/popcorntime/vendor/enqueue/dbal/DbalSubscriptionConsumer.php(117): call_user_func()\n
      #20 /var/www/popcorntime/vendor/enqueue/enqueue/Consumption/QueueConsumer.php(264): Enqueue\Dbal\DbalSubscriptionConsumer->consume()\n
      #21 /var/www/popcorntime/vendor/enqueue/enqueue/Symfony/Client/ConsumeCommand.php(144): Enqueue\Consumption\QueueConsumer->consume()\n
      #22 /var/www/popcorntime/vendor/symfony/console/Command/Command.php(298): Enqueue\Symfony\Client\ConsumeCommand->execute()\n
      #23 /var/www/popcorntime/vendor/symfony/console/Application.php(1042): Symfony\Component\Console\Command\Command->run()\n
      #24 /var/www/popcorntime/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()\n
      #25 /var/www/popcorntime/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()\n
      #26 /var/www/popcorntime/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()\n
      #27 /var/www/popcorntime/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()\n
      #28 /var/www/popcorntime/bin/console(42): Symfony\Component\Console\Application->run()\n
      #29 {main}
      """
  ]
]
```
```
cURL error 97: Can't complete SOCKS5 connection to rutorc6mqdinc4cz.onion. (1) (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://rutorc6mqdinc4cz.onion/browse/0/1/0/0
```

**Comment by harisnaeemofficial** [comment]
check that the tor proxy is running on the Sock5 port.

run this in the console: curl --socks5 localhost:9050 google.com

it should return 
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

**Comment by ottar-eten-yod** [comment]
It does return that.

**Comment by harisnaeemofficial** [comment]
Are you using ubuntu on oracle free cloud server?

**Comment by ivan1986** [comment]
@harisnaeemofficial yes - 22.04

**Comment by ottar-eten-yod** [comment]
> Are you using ubuntu on oracle free cloud server?

Not me personally, but I found the issue anyways. Some spiders do not use TOR. I am editing them to use it. 

The Rutor onion link's are dead so probably going to depreciate them.

**Comment by ivan1986** [comment]
it's ok, that some spiders not use tor - if tracker has good stable address without ban use it

**Comment by ottar-eten-yod** [comment]
The issue is, some ISP's block certain torrent websites like Eztv, RuTracker. So TOR should be used in that case.

Maybe a check can be conducted, if it returns timed out then it will use TOR to try and connect?

**Comment by harisnaeemofficial** [comment]
Oh yes that was the problem some of the tor links were dead you should check the website for the new link and replace it in the file it should fix the issue .
I was also facing the same problem some day before.

**Comment by harisnaeemofficial** [comment]
> The issue is, some ISP's block certain torrent websites like Eztv, RuTracker. So TOR should be used in that case.
> 
> Maybe a check can be conducted, if it returns timed out then it will use TOR to try and connect?

Yes it a good idea. This should be implemented as well. Sometimes i also get timeout error

**Comment by ottar-eten-yod** [comment]
I will take a look into it. I am going to make a list to work on.

**Comment by ivan1986** [comment]
> The issue is, some ISP's block certain torrent websites like Eztv, RuTracker. So TOR should be used in that case.

it doesn’t matter if some provider blocks the site, in this case it is important for us that this site is accessible from the server
